import { Teacher, Deal, Expense } from "../types";

export const DEMO_TEACHERS: Omit<Teacher, "id">[] = [
  {
    name: "আরিফ আহমেদ",
    phone: "01711223344",
    photoUrl: "https://i.pravatar.cc/150?u=1",
    collegeName: "Gurudayal Govt. College",
    presentAddress: "Harua (হারুয়া)",
    permanentAddress: "Kishoreganj Sadar",
    education: {
      ssc: { year: "2015", group: "Science", gpa: "5.00" },
      hsc: { year: "2017", group: "Science", gpa: "5.00" },
      honours: { year: "2021", subject: "Physics", studyYear: "4th Year", gpa: "3.50" }
    },
    experience: "৩ বছরের অভিজ্ঞতা",
    hasCurrentTuition: true,
    interestedSubjectsAndClasses: "৯ম-১২শ শ্রেণী (পদার্থ, গণিত)",
    isMedical: false,
    isPublicUniversity: false,
    canTeachHSC: true,
    hscSubject: "Physics",
    facebookLink: "https://facebook.com/arif",
    studentIdUrl: "https://i.pravatar.cc/150?u=1",
    rating: 4.8,
    createdAt: Date.now(),
  },
  {
    name: "তানজিলা আক্তার",
    phone: "01822334455",
    photoUrl: "https://i.pravatar.cc/150?u=2",
    collegeName: "Gurudayal Govt. College",
    presentAddress: "Harua (হারুয়া)",
    permanentAddress: "Kishoreganj Sadar",
    education: {
      ssc: { year: "2016", group: "Arts", gpa: "4.80" },
      hsc: { year: "2018", group: "Arts", gpa: "4.90" },
      honours: { year: "2022", subject: "English", studyYear: "3rd Year", gpa: "3.60" }
    },
    experience: "২ বছরের অভিজ্ঞতা",
    hasCurrentTuition: true,
    interestedSubjectsAndClasses: "৬ষ্ঠ-১০ম শ্রেণী (ইংরেজি, বাংলা)",
    isMedical: false,
    isPublicUniversity: false,
    canTeachHSC: false,
    facebookLink: "",
    studentIdUrl: "",
    rating: 4.5,
    createdAt: Date.now(),
  },
  {
    name: "ডাঃ সজীব হাসান",
    phone: "01933445566",
    photoUrl: "https://i.pravatar.cc/150?u=3",
    collegeName: "Shaheed Syed Nazrul Islam Medical College",
    presentAddress: "Gaital (গাইট্যাল)",
    permanentAddress: "Dhaka",
    education: {
      ssc: { year: "2014", group: "Science", gpa: "5.00" },
      hsc: { year: "2016", group: "Science", gpa: "5.00" },
      honours: { year: "2021", subject: "MBBS", studyYear: "Completed", gpa: "N/A" }
    },
    experience: "৫ বছরের অভিজ্ঞতা",
    hasCurrentTuition: false,
    interestedSubjectsAndClasses: "HSC (জীববিজ্ঞান)",
    isMedical: true,
    medicalInstitution: "Shaheed Syed Nazrul Islam Medical College",
    isPublicUniversity: false,
    canTeachHSC: true,
    hscSubject: "Biology",
    facebookLink: "https://facebook.com/sajeeb",
    studentIdUrl: "https://i.pravatar.cc/150?u=3",
    rating: 4.9,
    createdAt: Date.now(),
  },
  {
    name: "রাকিবুল ইসলাম",
    phone: "01644556677",
    photoUrl: "https://i.pravatar.cc/150?u=4",
    collegeName: "Kishoreganj Polytechnic Institute",
    presentAddress: "Botrish (বত্রিশ)",
    permanentAddress: "Mymensingh",
    education: {
      ssc: { year: "2018", group: "Science", gpa: "4.50" },
      hsc: { year: "2020", group: "Science", gpa: "4.20" },
      honours: { year: "2024", subject: "Computer", studyYear: "1st Year", gpa: "3.80" }
    },
    experience: "১ বছরের অভিজ্ঞতা",
    hasCurrentTuition: true,
    interestedSubjectsAndClasses: "৫ম-৮ম শ্রেণী (গণিত, বিজ্ঞান)",
    isMedical: false,
    isPublicUniversity: false,
    canTeachHSC: false,
    facebookLink: "",
    studentIdUrl: "",
    rating: 4.7,
    createdAt: Date.now(),
  },
  {
    name: "ফারহানা ইয়াসমিন",
    phone: "01555667788",
    photoUrl: "https://i.pravatar.cc/150?u=5",
    collegeName: "Dhaka University",
    presentAddress: "Akhrakhabazar (আখড়াবাজার)",
    permanentAddress: "Kishoreganj Sadar",
    education: {
      ssc: { year: "2017", group: "Humanities", gpa: "4.60" },
      hsc: { year: "2019", group: "Humanities", gpa: "4.70" },
      honours: { year: "2023", subject: "Bangla", studyYear: "2nd Year", gpa: "3.40" }
    },
    experience: "নতুন",
    hasCurrentTuition: false,
    interestedSubjectsAndClasses: "১ম-৫ম শ্রেণী (সব বিষয়)",
    isMedical: false,
    isPublicUniversity: true,
    publicUniversityName: "Dhaka University",
    canTeachHSC: false,
    facebookLink: "https://facebook.com/farhana",
    studentIdUrl: "",
    rating: 4.2,
    createdAt: Date.now(),
  },
  {
    name: "মেহেদী হাসান",
    phone: "01788990011",
    photoUrl: "https://i.pravatar.cc/150?u=6",
    collegeName: "Gurudayal Govt. College",
    presentAddress: "Gaital (গাইট্যাল)",
    permanentAddress: "Kishoreganj Sadar",
    education: {
      ssc: { year: "2016", group: "Science", gpa: "5.00" },
      hsc: { year: "2018", group: "Science", gpa: "4.80" },
      honours: { year: "2022", subject: "Mathematics", studyYear: "3rd Year", gpa: "3.75" }
    },
    experience: "২ বছরের অভিজ্ঞতা",
    hasCurrentTuition: true,
    interestedSubjectsAndClasses: "৮ম-১০ম শ্রেণী (গণিত)",
    isMedical: false,
    isPublicUniversity: false,
    canTeachHSC: false,
    facebookLink: "",
    studentIdUrl: "",
    rating: 4.6,
    createdAt: Date.now(),
  },
  {
    name: "সাদিয়া আফরিন",
    phone: "01899001122",
    photoUrl: "https://i.pravatar.cc/150?u=7",
    collegeName: "Dhaka University",
    presentAddress: "Harua (হারুয়া)",
    permanentAddress: "Dhaka",
    education: {
      ssc: { year: "2015", group: "Science", gpa: "5.00" },
      hsc: { year: "2017", group: "Science", gpa: "5.00" },
      honours: { year: "2021", subject: "Chemistry", studyYear: "4th Year", gpa: "3.85" }
    },
    experience: "৪ বছরের অভিজ্ঞতা",
    hasCurrentTuition: true,
    interestedSubjectsAndClasses: "৯ম-১২শ শ্রেণী (রসায়ন)",
    isMedical: false,
    isPublicUniversity: true,
    publicUniversityName: "Dhaka University",
    canTeachHSC: true,
    hscSubject: "Chemistry",
    facebookLink: "",
    studentIdUrl: "",
    rating: 4.9,
    createdAt: Date.now(),
  },
];

export const DEMO_DEALS: Omit<Deal, "id">[] = [
  {
    tuitionId: "T-1001",
    tutorName: "আরিফ আহমেদ",
    tutorPhone: "01711223344",
    guardianPhone: "01700000001",
    studentClass: "Class 10",
    details: "Math & Physics, 3 days/week",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-01",
    confirmDate: "2024-03-05",
    commission: 2000,
    tuitionStatus: "Running",
    commissionStatus: "Paid",
    collectedBy: "Admin",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন শুরু হয়েছে" }],
  },
  {
    tuitionId: "T-1002",
    tutorName: "তানজিলা আক্তার",
    tutorPhone: "01822334455",
    guardianPhone: "01700000002",
    studentClass: "Class 8",
    details: "All subjects, 4 days/week",
    referrerName: "ফেসবুক",
    adminName: "Admin",
    selectionDate: "2024-03-02",
    confirmDate: "2024-03-06",
    commission: 1500,
    tuitionStatus: "Confirmed",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন কনফার্ম হয়েছে" }],
  },
  {
    tuitionId: "T-1003",
    tutorName: "ডাঃ সজীব হাসান",
    tutorPhone: "01933445566",
    guardianPhone: "01700000003",
    studentClass: "HSC 2nd Year",
    details: "Biology, 2 days/week",
    referrerName: "বন্ধু",
    adminName: "Admin",
    selectionDate: "2024-03-03",
    confirmDate: "",
    commission: 3000,
    tuitionStatus: "Processing",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিচার সিলেক্ট করা হয়েছে" }],
  },
  {
    tuitionId: "T-1004",
    tutorName: "রাকিবুল ইসলাম",
    tutorPhone: "01644556677",
    guardianPhone: "01700000004",
    studentClass: "Class 12",
    details: "Physics & Chemistry",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-04",
    confirmDate: "2024-03-08",
    commission: 2500,
    tuitionStatus: "Rejected",
    commissionStatus: "Rejected",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "গার্ডিয়ান রিজেক্ট করেছে" }],
  },
  {
    tuitionId: "T-1005",
    tutorName: "ফারহানা ইয়াসমিন",
    tutorPhone: "01555667788",
    guardianPhone: "01700000005",
    studentClass: "Class 5",
    details: "General subjects",
    referrerName: "ফেসবুক",
    adminName: "Admin",
    selectionDate: "2024-03-05",
    confirmDate: "2024-03-10",
    commission: 1000,
    tuitionStatus: "Cancelled",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিচার ক্যান্সেল করেছে" }],
  },
  {
    tuitionId: "T-1006",
    tutorName: "কামরুল হাসান",
    tutorPhone: "01766778899",
    guardianPhone: "01700000006",
    studentClass: "Class 9",
    details: "Math & Science",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-06",
    confirmDate: "2024-03-12",
    commission: 1800,
    tuitionStatus: "Running",
    commissionStatus: "Paid",
    collectedBy: "Admin",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন শুরু হয়েছে" }],
  },
];

export const DEMO_EXPENSES: Omit<Expense, "id">[] = [
  {
    adminName: "Admin",
    amount: 500,
    purpose: "অফিস ভাড়া (আংশিক)",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 200,
    purpose: "ইন্টারনেট বিল",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 1000,
    purpose: "বিজ্ঞাপন (ফেসবুক)",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 300,
    purpose: "চা-নাস্তা",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 150,
    purpose: "মোবাইল রিচার্জ",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
];
