import { Teacher, Deal, Expense } from "../types";

export const DEMO_TEACHERS: Omit<Teacher, "id">[] = [
  {
    name: "আরিফ আহমেদ",
    phone: "01711223344",
    institution: "বুয়েট",
    department: "সিএসই",
    area: "ধানমন্ডি",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.8,
    createdAt: Date.now(),
  },
  {
    name: "তানজিলা আক্তার",
    phone: "01822334455",
    institution: "ঢাকা বিশ্ববিদ্যালয়",
    department: "ইংরেজি",
    area: "উত্তরা",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.5,
    createdAt: Date.now(),
  },
  {
    name: "ডাঃ সজীব হাসান",
    phone: "01933445566",
    institution: "ডিএমসি",
    department: "এমবিবিএস",
    area: "ফার্মগেট",
    canTeachHSC: true,
    isMedical: true,
    rating: 4.9,
    createdAt: Date.now(),
  },
  {
    name: "রাকিবুল ইসলাম",
    phone: "01644556677",
    institution: "আইইউটি",
    department: "ইইই",
    area: "গাজীপুর",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.7,
    createdAt: Date.now(),
  },
  {
    name: "ফারহানা ইয়াসমিন",
    phone: "01555667788",
    institution: "এনএসইউ",
    department: "বিবিএ",
    area: "বনানী",
    canTeachHSC: false,
    isMedical: false,
    rating: 4.2,
    createdAt: Date.now(),
  },
  {
    name: "কামরুল হাসান",
    phone: "01766778899",
    institution: "কুয়েট",
    department: "মেকানিক্যাল",
    area: "মিরপুর",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.6,
    createdAt: Date.now(),
  },
  {
    name: "সুমাইয়া বিনতে",
    phone: "01877889900",
    institution: "জবি",
    department: "বাংলা",
    area: "পুরান ঢাকা",
    canTeachHSC: false,
    isMedical: false,
    rating: 4.3,
    createdAt: Date.now(),
  },
  {
    name: "জাহিদুল ইসলাম",
    phone: "01988990011",
    institution: "রুয়েট",
    department: "সিভিল",
    area: "রাজশাহী",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.4,
    createdAt: Date.now(),
  },
  {
    name: "নুসরাত জাহান",
    phone: "01699001122",
    institution: "চবি",
    department: "অর্থনীতি",
    area: "চট্টগ্রাম",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.1,
    createdAt: Date.now(),
  },
  {
    name: "আব্দুল্লাহ আল মামুন",
    phone: "01511223344",
    institution: "শাবিপ্রবি",
    department: "পদার্থবিজ্ঞান",
    area: "সিলেট",
    canTeachHSC: true,
    isMedical: false,
    rating: 4.5,
    createdAt: Date.now(),
  },
];

export const DEMO_DEALS: Omit<Deal, "id">[] = [
  {
    tuitionId: "T-1001",
    tutorName: "আরিফ আহমেদ",
    tutorPhone: "01711223344",
    guardianPhone: "01700000001",
    studentClass: "Class 10",
    details: "Math & Physics, 3 days/week",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-01",
    confirmDate: "2024-03-05",
    commission: 2000,
    tuitionStatus: "Running",
    commissionStatus: "Paid",
    collectedBy: "Admin",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন শুরু হয়েছে" }],
  },
  {
    tuitionId: "T-1002",
    tutorName: "তানজিলা আক্তার",
    tutorPhone: "01822334455",
    guardianPhone: "01700000002",
    studentClass: "Class 8",
    details: "All subjects, 4 days/week",
    referrerName: "ফেসবুক",
    adminName: "Admin",
    selectionDate: "2024-03-02",
    confirmDate: "2024-03-06",
    commission: 1500,
    tuitionStatus: "Confirmed",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন কনফার্ম হয়েছে" }],
  },
  {
    tuitionId: "T-1003",
    tutorName: "ডাঃ সজীব হাসান",
    tutorPhone: "01933445566",
    guardianPhone: "01700000003",
    studentClass: "HSC 2nd Year",
    details: "Biology, 2 days/week",
    referrerName: "বন্ধু",
    adminName: "Admin",
    selectionDate: "2024-03-03",
    confirmDate: "",
    commission: 3000,
    tuitionStatus: "Processing",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিচার সিলেক্ট করা হয়েছে" }],
  },
  {
    tuitionId: "T-1004",
    tutorName: "রাকিবুল ইসলাম",
    tutorPhone: "01644556677",
    guardianPhone: "01700000004",
    studentClass: "Class 12",
    details: "Physics & Chemistry",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-04",
    confirmDate: "2024-03-08",
    commission: 2500,
    tuitionStatus: "Rejected",
    commissionStatus: "Rejected",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "গার্ডিয়ান রিজেক্ট করেছে" }],
  },
  {
    tuitionId: "T-1005",
    tutorName: "ফারহানা ইয়াসমিন",
    tutorPhone: "01555667788",
    guardianPhone: "01700000005",
    studentClass: "Class 5",
    details: "General subjects",
    referrerName: "ফেসবুক",
    adminName: "Admin",
    selectionDate: "2024-03-05",
    confirmDate: "2024-03-10",
    commission: 1000,
    tuitionStatus: "Cancelled",
    commissionStatus: "Pending",
    collectedBy: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিচার ক্যান্সেল করেছে" }],
  },
  {
    tuitionId: "T-1006",
    tutorName: "কামরুল হাসান",
    tutorPhone: "01766778899",
    guardianPhone: "01700000006",
    studentClass: "Class 9",
    details: "Math & Science",
    referrerName: "সরাসরি",
    adminName: "Admin",
    selectionDate: "2024-03-06",
    confirmDate: "2024-03-12",
    commission: 1800,
    tuitionStatus: "Running",
    commissionStatus: "Paid",
    collectedBy: "Admin",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "টিউশন শুরু হয়েছে" }],
  },
];

export const DEMO_EXPENSES: Omit<Expense, "id">[] = [
  {
    adminName: "Admin",
    amount: 500,
    purpose: "অফিস ভাড়া (আংশিক)",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 200,
    purpose: "ইন্টারনেট বিল",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 1000,
    purpose: "বিজ্ঞাপন (ফেসবুক)",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 300,
    purpose: "চা-নাস্তা",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
  {
    adminName: "Admin",
    amount: 150,
    purpose: "মোবাইল রিচার্জ",
    createdAt: Date.now(),
    history: [{ date: new Date().toISOString(), log: "খরচ যোগ করা হয়েছে" }],
  },
];
